# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RequestManager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RequestManager
  # Networking
  pod 'Alamofire'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'SwiftLint'


  target 'RequestManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RequestManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
